---
version: "3"

services:
  portmap-client:
    image: dmotte/portmap-client
    build: build
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/portmap-client/known_hosts:/known_hosts:ro
      - ./volumes/portmap-client/ssh_client_key:/ssh_client_key:ro
    environment:
      SSH_SERVER: 10.0.2.15
      SSH_PORT: 2222
      SSH_USERNAME: portmap
      FORWARDINGS: 8080:webserver:80,8081:google.it:80
  webserver:
    image: nginx
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/webserver/www:/usr/share/nginx/html:ro
