name: docker-description

on:
  push:
    branches: [main]
    paths:
      - README.md

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: dmotte
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dmotte/portmap-client
          short-description: Docker image you can use to expose a local TCP port to the internet using an SSH tunnel
