name: Docker

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dmotte
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: docker-build
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64
          push: true
          tags: dmotte/portmap-client

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: dmotte
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dmotte/portmap-client
          short-description: Docker image you can use to expose a local TCP port to the internet using an SSH tunnel
